"""Whole-Python probe questions used only by the acceptance tests."""

from __future__ import annotations


PROBE_QUESTIONS = [
    {
        "area": "interpreter",
        "question": "python -i 和直接运行 .py 文件有什么区别？",
        "concept_id": "Concept:interactive_mode",
    },
    {
        "area": "variables",
        "question": "变量赋值和数学里的等号一样吗？",
        "concept_id": "Concept:name_binding",
    },
    {
        "area": "numbers",
        "question": "为什么 0.1 + 0.2 不是 0.3？",
        "concept_id": "Concept:floating_point",
    },
    {
        "area": "strings",
        "question": "字符串前面的 r 是什么意思？",
        "concept_id": "Concept:raw_string",
    },
    {
        "area": "lists",
        "question": "append 和 extend 有什么区别？",
        "concept_id": "Concept:list_methods",
    },
    {
        "area": "tuples",
        "question": "tuple 为什么不能改？",
        "concept_id": "Concept:tuple_immutability",
    },
    {
        "area": "dictionaries",
        "question": "dict.get 和 d[key] 有什么区别？",
        "concept_id": "Concept:dictionary_get",
    },
    {
        "area": "sets",
        "question": "set 为什么会去重？",
        "concept_id": "Concept:set_uniqueness",
    },
    {
        "area": "conditions",
        "question": "if elif else 到底怎么执行？",
        "concept_id": "Concept:conditional_execution",
    },
    {
        "area": "loops",
        "question": "while 条件什么时候停？",
        "concept_id": "Concept:while_condition",
    },
    {
        "area": "range",
        "question": "range(5) 为什么没有 5？",
        "concept_id": "Concept:range_stop_boundary",
    },
    {
        "area": "functions",
        "question": "默认参数为什么不要写成 []？",
        "concept_id": "Concept:mutable_default_argument",
    },
    {
        "area": "arguments",
        "question": "*args 和 **kwargs 是什么？",
        "concept_id": "Concept:arbitrary_arguments",
    },
    {
        "area": "scope",
        "question": "global 和 nonlocal 有什么区别？",
        "concept_id": "Concept:scope_namespace",
    },
    {
        "area": "modules",
        "question": "import 一个模块时 Python 去哪里找？",
        "concept_id": "Concept:module_search_path",
    },
    {
        "area": "packages",
        "question": "__init__.py 是干嘛的？",
        "concept_id": "Concept:package_initialization",
    },
    {
        "area": "files",
        "question": "with open(...) 比直接 open 好在哪里？",
        "concept_id": "Concept:file_context_manager",
    },
    {
        "area": "json",
        "question": "json.dumps 和 json.loads 反了吗？",
        "concept_id": "Concept:json_serialization",
    },
    {
        "area": "exceptions",
        "question": "try except finally 的 finally 一定会执行吗？",
        "concept_id": "Concept:exception_finally",
    },
    {
        "area": "classes",
        "question": "self 到底是谁？",
        "concept_id": "Concept:instance_method_self",
    },
    {
        "area": "inheritance",
        "question": "子类重写方法是什么意思？",
        "concept_id": "Concept:method_override",
    },
    {
        "area": "iterators",
        "question": "iter 和 next 是什么关系？",
        "concept_id": "Concept:iterator_protocol",
    },
    {
        "area": "generators",
        "question": "yield 和 return 有什么区别？",
        "concept_id": "Concept:generator_yield",
    },
    {
        "area": "comprehensions",
        "question": "列表推导式什么时候不该用？",
        "concept_id": "Concept:list_comprehension",
    },
    {
        "area": "venv",
        "question": "venv 为什么能隔离包？",
        "concept_id": "Concept:virtual_environment",
    },
    {
        "area": "pip",
        "question": "pip install 装到哪里去了？",
        "concept_id": "Concept:pip_install_location",
    },
    {
        "area": "stdlib",
        "question": "datetime 和 time 有什么区别？",
        "concept_id": "Concept:standard_library_datetime",
    },
    {
        "area": "regex",
        "question": "re.match 和 re.search 有什么区别？",
        "concept_id": "Concept:regex_search",
    },
    {
        "area": "debugging",
        "question": "NameError 和 SyntaxError 怎么区分？",
        "concept_id": "Concept:debugging_error_types",
    },
    {
        "area": "decorators",
        "question": "装饰器 @property 到底改了什么？",
        "concept_id": "Concept:decorator",
    },
]


# The canonical D01-D22 conversation-arbitration matrix.  These are deliberately
# plain data so the acceptance runner can exercise every row through the public
# ``next_session_step`` contract without a model or network connection.
DIALOGUE_ACCEPTANCE_CASES = [
    {
        "case_id": "D01",
        "precondition": "empty",
        "turns": [{"message": "什么是 Python list？"}],
        "expected_relation": "start",
        "expected_topic": "Concept:list",
        "expected_selection_usage": "absent",
        "expected_workflow_action": "initialize",
        "required_visible": [],
        "forbidden_visible": ["Selected Node:", "Topic Transition:"],
    },
    {
        "case_id": "D02",
        "precondition": "dictionary",
        "turns": [{"message": "这是啥意思？"}],
        "expected_relation": "clarify_current",
        "expected_topic": "Concept:dict",
        "expected_selection_usage": "absent",
        "expected_workflow_action": "continue",
        "expected_resolved_terms": ["dictionary"],
        "pedagogy_must_be_unchanged": True,
        "required_visible": [],
        "forbidden_visible": ["Selected Node:", "Topic Transition:", "请告诉我一个具体问题"],
    },
    {
        "case_id": "D03",
        "precondition": "dictionary",
        "turns": [{"message": "这是啥意思？", "selected_node_id": "Concept:len"}],
        "expected_relation": "kg_explore",
        "expected_topic": "Concept:len",
        "expected_selection_usage": "used",
        "expected_workflow_action": "initialize",
        "required_visible": ["Selected Node: len", "Topic Transition: dictionary → len", "Previous Context:"],
        "forbidden_visible": ["Not used for this response"],
        "forbidden_retrieval": ["怎么学习dictionary？"],
    },
    {
        "case_id": "D04",
        "precondition": "len",
        "turns": [{"message": "len 对字符串返回什么？", "selected_node_id": "Concept:len"}],
        "expected_relation": "continue",
        "expected_topic": "Concept:len",
        "expected_selection_usage": "used",
        "expected_workflow_action": "continue",
        "required_visible": ["Selected Node: len"],
        "forbidden_visible": ["Topic Transition:", "Not used for this response"],
        "expected_topic_count": 1,
    },
    {
        "case_id": "D05",
        "precondition": "dictionary",
        "turns": [{"message": "dictionary 怎么添加键值对？", "selected_node_id": "Concept:len"}],
        "expected_relation": "kg_explore",
        "expected_topic": "Concept:len",
        "expected_selection_usage": "used",
        "expected_workflow_action": "initialize",
        "required_visible": ["Selected Node: len"],
        "forbidden_visible": ["Not used for this response"],
    },
    {
        "case_id": "D06",
        "precondition": "dictionary",
        "turns": [{"message": "先不说 dictionary，讲讲 function"}],
        "expected_relation": "switch_topic",
        "expected_topic": "Concept:function",
        "expected_selection_usage": "absent",
        "expected_workflow_action": "initialize",
        "required_visible": ["Topic Transition: dictionary → function", "Previous Context:"],
        "forbidden_visible": ["Selected Node:", "Resumed Context:"],
        "preserved_topics": ["Concept:dict"],
    },
    {
        "case_id": "D07",
        "precondition": "dictionary",
        "turns": [{"message": "先不说 dictionary，讲讲 function"}, {"message": "back"}],
        "expected_relation": "resume_previous",
        "expected_topic": "Concept:dict",
        "expected_selection_usage": "absent",
        "expected_workflow_action": "restore",
        "required_visible": ["Topic Transition: function → dictionary", "Resumed Context:"],
        "forbidden_visible": ["Selected Node:", "Previous Context:"],
        "restore_exact_topic": "Concept:dict",
    },
    {
        "case_id": "D08",
        "precondition": "history_list_dictionary_function",
        "turns": [{"message": "回到之前讲 list 的地方"}],
        "expected_relation": "resume_named",
        "expected_topic": "Concept:list",
        "expected_selection_usage": "absent",
        "expected_workflow_action": "restore",
        "required_visible": ["Topic Transition: function → list", "Resumed Context:"],
        "forbidden_visible": ["Topic Transition: function → dictionary"],
        "restore_exact_topic": "Concept:list",
    },
    {
        "case_id": "D09",
        "precondition": "empty",
        "turns": [{"message": "back"}],
        "expected_relation": "unresolved",
        "expected_topic": None,
        "expected_selection_usage": "absent",
        "expected_workflow_action": "preserve_without_advance",
        "required_visible": ["no previous topic exists"],
        "forbidden_visible": ["Topic Transition:", "Selected Node:"],
    },
    {
        "case_id": "D10",
        "precondition": "list",
        "turns": [{"message": "那 append 呢？"}],
        "expected_relation": "continue",
        "expected_topic": "Concept:list",
        "expected_selection_usage": "absent",
        "expected_workflow_action": "continue",
        "expected_resolved_terms": ["list", "append"],
        "required_visible": [],
        "forbidden_visible": ["Selected Node:", "Topic Transition:"],
    },
    {
        "case_id": "D11",
        "precondition": "list",
        "turns": [{"message": "我说的“它”是 tuple，不是 list"}],
        "expected_relation": "switch_topic",
        "expected_topic": "Concept:tuple",
        "expected_selection_usage": "absent",
        "expected_workflow_action": "initialize",
        "required_visible": ["Topic Transition: list → tuple"],
        "forbidden_visible": ["Topic Transition: tuple → list"],
    },
    {
        "case_id": "D12",
        "precondition": "dictionary_confidence",
        "turns": [{"message": "先不说 dictionary，讲讲 while loop"}],
        "expected_relation": "switch_topic",
        "expected_topic": "Concept:while_loop",
        "expected_selection_usage": "absent",
        "expected_workflow_action": "initialize",
        "required_visible": ["Topic Transition: dictionary → while loop"],
        "forbidden_visible": ["Selected Node:"],
        "new_topic_must_not_inherit_confidence": True,
    },
    {
        "case_id": "D13",
        "precondition": "dictionary_confidence",
        "turns": [{"message": "先不说 dictionary，讲讲 while loop"}, {"message": "back"}],
        "expected_relation": "resume_previous",
        "expected_topic": "Concept:dict",
        "expected_selection_usage": "absent",
        "expected_workflow_action": "restore",
        "required_visible": ["Topic Transition: while loop → dictionary", "Resumed Context:"],
        "forbidden_visible": ["Selected Node:"],
        "restore_exact_topic": "Concept:dict",
    },
    {
        "case_id": "D14",
        "precondition": "dictionary",
        "turns": [{"message": "今天天气怎么样？", "selected_node_id": "Concept:len"}],
        "expected_relation": "kg_explore",
        "expected_topic": "Concept:len",
        "expected_selection_usage": "used",
        "expected_workflow_action": "initialize",
        "required_visible": ["Selected Node: len"],
        "forbidden_visible": ["Not used for this response"],
    },
    {
        "case_id": "D15",
        "precondition": "dictionary_with_back_stack",
        "turns": [{"message": "你好"}],
        "expected_relation": "greeting",
        "expected_topic": "Concept:dict",
        "expected_selection_usage": "absent",
        "expected_workflow_action": "preserve_without_advance",
        "required_visible": [],
        "forbidden_visible": ["Selected Node:", "Topic Transition:"],
        "projection_must_be_preserved": True,
    },
    {
        "case_id": "D16",
        "precondition": "dictionary",
        "turns": [{"message": "dictionary 的 key 怎么取？", "provider_override": "rewrite_to_len"}],
        "expected_relation": "continue",
        "expected_topic": "Concept:dict",
        "expected_selection_usage": "absent",
        "expected_workflow_action": "continue",
        "required_visible": [],
        "forbidden_visible": ["Selected Node:", "Topic Transition: dictionary → len"],
        "forbidden_retrieval": ["Python len usage"],
    },
    {
        "case_id": "D17",
        "precondition": "dictionary",
        "turns": [{"message": "再举一个例子", "provider_override": "intent_unknown"}],
        "expected_relation": "continue",
        "expected_topic": "Concept:dict",
        "expected_selection_usage": "absent",
        "expected_workflow_action": "continue",
        "required_visible": [],
        "forbidden_visible": ["请告诉我一个具体问题", "Topic Transition:"],
    },
    {
        "case_id": "D18",
        "precondition": "dictionary",
        "turns": [{"message": "这是啥意思？", "selected_node_id": "Concept:len", "fail_during_response": True}],
        "expected_relation": "kg_explore",
        "expected_topic": "Concept:dict",
        "expected_selection_usage": "used",
        "expected_workflow_action": "initialize",
        "required_visible": [],
        "forbidden_visible": ["Selected Node:", "Topic Transition:"],
        "failed_turn": True,
    },
    {
        "case_id": "D19",
        "precondition": "dictionary",
        "turns": [
            {"message": "这是啥意思？", "selected_node_id": "Concept:len"},
            {"message": "继续"},
        ],
        "expected_relation": "continue",
        "expected_topic": "Concept:len",
        "expected_selection_usage": "absent",
        "expected_workflow_action": "continue",
        "required_visible": [],
        "required_visible_by_turn": [[0, "Selected Node: len"]],
        "forbidden_visible": ["Selected Node:", "Topic Transition:"],
    },
    {
        "case_id": "D20",
        "precondition": "dictionary",
        "turns": [{"message": "先不说 dictionary，讲讲 function", "selected_node_id": "Concept:len"}],
        "expected_relation": "kg_explore",
        "expected_topic": "Concept:len",
        "expected_selection_usage": "used",
        "expected_workflow_action": "initialize",
        "required_visible": [
            "Selected Node: len",
            "Previous Context:",
        ],
        "forbidden_visible": ["已选节点", "话题切换", "Not used for this response"],
        "answer_language": "Chinese",
        "context_bridge_language": "Chinese",
    },
    {
        "case_id": "D21",
        "precondition": "function",
        "turns": [
            {
                "message": "你好，今天过得怎么样？我们先随便聊两句。",
                "selected_node_id": "Concept:len",
            }
        ],
        "expected_relation": "kg_explore",
        "expected_intent": "concept_question",
        "expected_topic": "Concept:len",
        "expected_selection_usage": "used",
        "expected_workflow_action": "initialize",
        "required_visible": ["Selected Node: len"],
        "forbidden_visible": ["Not used for this response"],
    },
    {
        "case_id": "D22",
        "precondition": "function",
        "turns": [
            {
                "message": "我们随便聊聊 list 的切片",
                "selected_node_id": "Concept:len",
            }
        ],
        "expected_relation": "kg_explore",
        "expected_intent": "concept_question",
        "expected_topic": "Concept:len",
        "expected_selection_usage": "used",
        "expected_workflow_action": "initialize",
        "expected_resolved_terms": ["list", "切片"],
        "required_visible": [
            "Selected Node: len",
        ],
        "forbidden_visible": ["Not used for this response"],
    },
]
